### ISSUE TITLE
can't build  dockerfile

### ISSUE THREAD

**Issue by heycyril** [jordic/file_server#12]
When I built the image through Dockerfile, why can't I build it successfully? I didn't install the go locale, i just  cloned your code from github, and then built the image through Dockerfile.

Step 3 : ADD main /
Lstat main: no such file or directory

so I changed the main in Dockerfile to  main.go

Sending build context to Docker daemon 83.54 MB
Step 1 : FROM scratch
 --->
Step 2 : MAINTAINER
 ---> Using cache
 ---> 205bcd0bc6a3
Step 3 : ADD main.go /
 ---> Using cache
 ---> 0bb996fe9c59
Step 4 : VOLUME "/tmp"
 ---> Using cache
 ---> 54550e394aae
Step 5 : EXPOSE 8080
 ---> Using cache
 ---> c53243f85fb7
Step 6 : CMD /main.go
 ---> Using cache
 ---> 879fbb6879df
Successfully built 879fbb6879df

After the construction is successful, but it can't be successful for run.
 Docker run -d -v /data/ftproot:/tmp -p 8300:8080 gsy36559067/fileserver:0.6

logs :
[root@master file_server]# docker logs -f 19f592f7f805
Panic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
        Panic: standard_init_linux.go:175: exec user process caused "exec format error"
Goroutine 1 [running, locked to thread]:
Panic(0x7e9de0, 0xc8201205b0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
Github.com/urfave/cli.HandleAction.func1(0xc8200ef2e8)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
Panic(0x7e9de0, 0xc8201205b0)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
Github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200eebf8, 0xc82001a0c8, 0xc8200eed08)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
Github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820051630, 0x7f99ed60e728, 0xc8201205b0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
Main.glob.func8(0xc82006ea00, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74e5e0, 0x8ffda0, 0x13, 0x846308, 0x4, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74e5e0, 0x8ffda0, 0x13, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
Github.com/urfave/cli.HandleAction(0x74e5e0, 0x8ffda0, 0xc82006ea00, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
Github.com/urfave/cli.Command.Run(0x8491b8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df0e0, 0x51, 0x0, ...)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
Github.com/urfave/cli.(*App).Run(0xc820001500, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
Main.main()
        /go/src/github.com/opencontainers/runc/main.go:137 +0xe24

so i don't know what to do,Can you help me, thank you

**Comment by heycyril** [comment]
i use
docker build -t cyril/fileserver:0.6   .

**Comment by jordic** [comment]
To build the docker image you first need to build the go package, the dockerfile expects to have a main binary on the root folder. The project still doesn't have a multistep docker image. (PR welcome)

**Comment by heycyril** [comment]
OK, i will continue to learn it, I hope I can learn soon.
